resources:
  - name: repo
    type: git
    source: 
      uri: https://github.com/Naveen-GDTC/repo
      branch: main


jobs:
  - name: read-secret
    plan:
      - get: repo
      - task: show-secret
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: hashicorp/vault
          outputs:
            - name: credentials 
          run:
            path: sh
            args:
              - -c
              - |
                export VAULT_ADDR='http://192.168.1.188:8200'
                export VAULT_TOKEN='token'
 
                USERNAME=$(vault kv get -field=username secret/cred)
                PASSWORD=$(vault kv get -field=password secret/cred)
                STOCK_CODE=$(vault kv get -field=stock_code secret/cred)
                
                echo $USERNAME > credentials/username.txt
                echo $PASSWORD > credentials/password.txt
                echo $STOCK_CODE > credentials/stock_code.txt

      - task: selenium-python-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: python
              tag: "3.9"
          inputs:
            - name: repo
            - name: credentials
          run:
            path: sh
            args:
              - -c
              - |
                apt-get update && apt-get install -y wget unzip curl libxi6 libgconf-2-4 libnss3 libgbm-dev xdg-utils

                wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                dpkg -i google-chrome-stable_current_amd64.deb || apt-get install -f -y

                wget https://storage.googleapis.com/chrome-for-testing-public/128.0.6613.84/linux64/chromedriver-linux64.zip
                unzip chromedriver-linux64.zip
                mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver

                chmod +x /usr/local/bin/chromedriver

                # Install Python packages
                pip install selenium   
                pip install hvac 
                pip install pandas
                pip install openpyxl

                export STOCK_CODE=$(cat credentials/stock_code.txt)
                export USERNAME=$(cat credentials/username.txt)
                export PASSWORD=$(cat credentials/password.txt)

 
                python3 repo/sel_script.py

                pip install psycopg2
                pip install pandas
                python3 repo/trigger_sel.py
